name: Merged main branch
on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  trigger-mirror:
    if: github.repository == 'aki-kii/zenn-private'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app_id: ${{ vars.MIRROR_APP_ID }}
          private_key: ${{ secrets.MIRROR_PRIVATE_KEY }}
          repositories: zenn
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git remote add mirror https://github.com/aki-kii/zenn.git
          git push mirror -f
